### ISSUE TITLE
[Documentation] Detaillierte Stakeholder-Analyse

### ISSUE THREAD

**Issue by Witteborn** [HWR-Berlin-SWE-I-Gruppe-2-Team-3-2021/Dokumentation#2]
## Detailed Description

Wir sollen eine detaillierte Stakeholder-Analyse erstellen, hierfür gibt es 5 von 100 Punkte.

#### Noch ausstehend
- [x] Rechtschreib korrektur
- [x] Kommentare entfernen
- [x] Literatur von Alan Cooper ins Literaturverzeichniss
- [x] Verweise in Ausblick hinzufügen
- [x] Dokumentationsschablone nach Kleuker hinzufügen
	- [x] Layout
	- [x] Inhalt fertig
- [x] Tabellenform der Stakeholderliste mit Rolle, Beschreibung, Konkreten vertreter, Verfügbarkeit, Wissensgebiet und Begründung
	- [x] Layout
	- [x] Inhalt fertig

- [x] Leerseite im Anhang entfernen (Nicht die Seite mit dem Titel sondern die danach) falls es geht
- [x] Review
	- [x] Felix
	- [x] Marcus
	- [x] Dennis

## Possible Implementation

LaTeX  Datei

**Comment by MK2112** [comment]
Noch ein paar Kleinigkeiten, die mir mit dem letzten Commit aufgefallen waren und die noch adressiert werden müssen. Falls einer von euch das machen kann:

Wer oder was sind Stakeholder*innen
- Zitatquelle angeben
- Interessensgrund des Gesetzgebers in Tabelle angeben

Dozent*innen
- "..." noch mit Text ersetzen
