### ISSUE TITLE
[Bug] Manuelles zusammenfügen der UML-Diagramme

### ISSUE THREAD

**Issue by Witteborn** [HWR-Berlin-SWE-I-Gruppe-2-Team-3-2021/Dokumentation#26]
# The Issue
Die UML-Diagramme sollen als eine Datei zusammen abgegeben werden
Siehe #25 

Am einfachsten ist es glaube ich sobald #3 und #4 Fertig sind diese manuell zu mergen.

**Comment by MK2112** [comment]
Ok, ich warte auf #20 und denk mir dann nen neues Coversheet aus.

**Comment by MK2112** [comment]
Hab nochmal geguckt. Gefordert ist ja aber eine .ZIP-Datei mit dem Namen `UML_IT20_KursB_TeamNr` (z.B. UML_IT20_KursB_Team5)
Was da nun reinkommt und wie das benannt ist, dazu steht nix. Nur wenns ne .ZIP ist, die gefordert ist, dann wird das sicherlich mehrere Dateien (sprich je für Diagramm eine PDF) implizieren, die wir einreichen sollen.

**Comment by Witteborn** [comment]
Vielen Dank! Ich schau mir mal an welche Optionen wir haben, ggf. ist es möglich die PDFs über den Release-Workflow in Zip- Dateien zu verpacken.
